[project]
name = "my-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "frozen-flask==1.0.2",
    "pydantic==2.12.5",
    "pyyaml==6.0.3",
    "ruff==0.15.0",
    "typer==0.21.1",
    "watchdog==6.0.0",
]
